import Foundation

// MARK: - Hobbie

enum Hobbie: String, CaseIterable, Codable {
    
    case football = "⚽️ Футбол"
    case basketball = "🏀 Баскетбол"
    case bigTennis = "🎾 Большой теннис"
    case volleyball = "🏐 Воллейбол"
    case billiard = "🎱 Бильярд"
    case tableTennis = "🏓 Настольный теннис"
    case hockey = "🏒 Хоккей"
    case golf = "⛳️ Гольф"
    case diving = "🤿 Дайвинг"
    case boxing = "🥊 Бокс"
    case skateboarding = "🛹 Скейтбординг"
    case rollerSkate = "🛼 Катание на роликах"
    case iceSkate = "⛸️ Катание на коньках"
    case ski = "⛷️ Катание на лыжах"
    case snowboarding = "🏂 Сноубординг"
    case parachute = "🪂 Прыжки с парашютом"
    case wightlifting = "🏋️‍♂️ Тяжелая атлетика"
    case wrestling = "🤼‍♂️ Борьба"
    case gymnastics = "🤸‍♂️ Гимнастика"
    case fencing = "🤺 Фехтование"
    case handball = "🤾 Гандбол"
    case jockey = "🏇 Жокей"
    case yoga = "🧘 Йога"
    case surfing = "🏄 Сёрфинг"
    case swimming = "🏊 Плавание"
    case rowing = "🚣 Гребля"
    case climbing = "🧗 Скалолазание"
    case cycling = "🚴 Езда на велосипеде"
    case magic = "🪄 Фокусы"
    case painting = "🎨 Рисование"
    case singing = "🎤 Пение"
    case piano = "🎹 Игра на пианино"
    case drums = "🥁 Игра на барабанах"
    case guitar = "🎸 Игра на гитаре"
    case violin = "🎻 Игра на скрипке"
    case chess = "♟️ Шахматы"
    case bowling = "🎳 Боулинг"
    case gaming = "🎮 Гейминг"
    case programming = "💻 Программирование"
    case travelling = "✈️ Путешествия"
}
